### ISSUE TITLE
binder/follow 字体模糊问题

### ISSUE THREAD

**Issue by jinmarcus** [07akioni/vueuc#90]
在使用binder/follow渲染的下拉菜单弹出的选项中的菜单有时候会出现字体模糊的情况，我找了一下原因
原因是在下拉菜单的浮层中使用了transform: translateX或translateY中的数字不是整数引起的

比如以下会出现字体模糊：
![image](https://user-images.githubusercontent.com/17996289/134458537-27758bf8-fd1b-4b84-b309-a0475cc1f7d1.png)
```
<div class="v-binder-follower-content" v-placement="bottom-start" style="width: 170px; min-width: 170px; transform: translateX(666.5px) translateY(215.5px); transform-origin: left top;">
</div>
```

但是如果translateX或translateY中的像素是整数就不会，如下就不会出现模糊
![image](https://user-images.githubusercontent.com/17996289/134449271-b341210b-4b20-4d1e-be87-59066266e9cc.png)
```
<div class="v-binder-follower-content" v-placement="bottom-start" style="width: 170px; min-width: 170px; transform: translateX(671px) translateY(206px); transform-origin: left top;">
</div>
```

应该是修改：
https://github.com/07akioni/vueuc/blob/e2273d9ed4f47cd1e02db0ebc0911a6fe066d6ef/src/binder/src/Follower.ts#L194

修改为：
```
follower.style.transform = `translateX(${parseInt(left)}px) translateY(${parseInt(top)}px) ${transform}`
```

如果这样不行的话，我觉得只有修改：
https://github.com/07akioni/vueuc/blob/e2273d9ed4f47cd1e02db0ebc0911a6fe066d6ef/src/binder/src/get-placement-style.ts#L138
这个里面的值了。

作者是否可以修复一下呢？

**Comment by 07akioni** [comment]
```
 follower.style.transform = `translateX(${left}) translateY(${top}) ${transform}` 
```
改这里就行，来个 PR？
